<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>SmartStore.Core</AssemblyName>
    <RootNamespace>SmartStore.Core</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.1.2" />
    <PackageReference Include="Autofac" Version="8.1.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="HtmlSanitizer" Version="8.2.871" />
    <PackageReference Include="log4net" Version="3.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.4.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="obj\**" />
    <Compile Remove="bin\**" />
    <Compile Remove="Fakes\**" />
    <Compile Remove="Packaging\**" />
    <Compile Remove="IO\VirtualPath\**" />
    <Compile Remove="Security\PermissionAttribute.cs" />
    <Compile Remove="Infrastructure\ApplicationStart.cs" />
    <Compile Remove="Utilities\SmartSyndicationFeed.cs" />
    <Compile Remove="Logging\log4net\Log4netLoggerFactory.cs" />
    <Compile Remove="Extensions\HttpExtensions.cs" />
    <Compile Remove="Caching\MemoryCacheManager.cs" />
    <EmbeddedResource Remove="obj\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="Fakes\**" />
    <EmbeddedResource Remove="Packaging\**" />
    <EmbeddedResource Remove="IO\VirtualPath\**" />
    <None Remove="obj\**" />
    <None Remove="bin\**" />
    <None Remove="Fakes\**" />
    <None Remove="Packaging\**" />
    <None Remove="IO\VirtualPath\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="packages.config" />
    <None Remove="app.config" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\AssemblySharedInfo.cs" Link="Properties\AssemblySharedInfo.cs" />
    <Compile Include="..\..\AssemblyVersionInfo.cs" Link="Properties\AssemblyVersionInfo.cs" />
  </ItemGroup>
</Project>
