<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SmartStore.Shipping</RootNamespace>
    <AssemblyName>SmartStore.Shipping</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Release;EFMigrations;PluginDev</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\SmartStore.Core\SmartStore.Core.csproj" />
    <ProjectReference Include="..\..\Libraries\SmartStore.Services\SmartStore.Services.csproj" />
    <ProjectReference Include="..\..\Presentation\SmartStore.Web.Framework\SmartStore.Web.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
