<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SmartStore.Shipping</RootNamespace>
    <AssemblyName>SmartStore.Shipping</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.1.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\SmartStore.Core\SmartStore.Core.csproj" />
    <ProjectReference Include="..\..\Libraries\SmartStore.Services\SmartStore.Services.csproj" />
    <ProjectReference Include="..\..\Libraries\SmartStore.Data\SmartStore.Data.csproj" />
    <ProjectReference Include="..\..\Presentation\SmartStore.Web.Framework\SmartStore.Web.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="obj\**" />
    <Compile Remove="bin\**" />
    <EmbeddedResource Remove="obj\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="obj\**" />
    <None Remove="bin\**" />
  </ItemGroup>

</Project>
