<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SmartStore.Services</RootNamespace>
    <AssemblyName>SmartStore.Services</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.0.0" />
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartStore.Core\SmartStore.Core.csproj" />
    <ProjectReference Include="..\SmartStore.Data\SmartStore.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\AssemblySharedInfo.cs" Link="Properties\AssemblySharedInfo.cs" />
    <Compile Include="..\..\AssemblyVersionInfo.cs" Link="Properties\AssemblyVersionInfo.cs" />
  </ItemGroup>
</Project>
