<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="8.0.0" />
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="Autofac" Version="7.1.0" />
    <PackageReference Include="AngleSharp" Version="1.1.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\SmartStore.Core\SmartStore.Core.csproj" />
    <ProjectReference Include="..\SmartStore.Data\SmartStore.Data.csproj" />
  </ItemGroup>
</Project>
