<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SmartStore.DevTools</RootNamespace>
    <AssemblyName>SmartStore.DevTools</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.3.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\SmartStore.Core\SmartStore.Core.csproj" />
    <ProjectReference Include="..\..\Libraries\SmartStore.Services\SmartStore.Services.csproj" />
    <ProjectReference Include="..\..\Presentation\SmartStore.Web.Framework\SmartStore.Web.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
