<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>SmartStore.DevTools</AssemblyName>
    <RootNamespace>SmartStore.DevTools</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.3.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\SmartStore.Core\SmartStore.Core.csproj" />
    <ProjectReference Include="..\..\Libraries\SmartStore.Services\SmartStore.Services.csproj" />
    <ProjectReference Include="..\..\Presentation\SmartStore.Web.Framework\SmartStore.Web.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="obj\**" />
    <Compile Remove="bin\**" />
    <EmbeddedResource Remove="obj\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="obj\**" />
    <None Remove="bin\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="packages.config" />
    <None Remove="Web.config" />
  </ItemGroup>
</Project>
