<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SmartStore.Tax</RootNamespace>
    <AssemblyName>SmartStore.Tax</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\SmartStore.Core\SmartStore.Core.csproj" />
    <ProjectReference Include="..\..\Libraries\SmartStore.Data\SmartStore.Data.csproj" />
    <ProjectReference Include="..\..\Libraries\SmartStore.Services\SmartStore.Services.csproj" />
    <ProjectReference Include="..\..\Presentation\SmartStore.Web.Framework\SmartStore.Web.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Description.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="web.config" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Content\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Localization\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Views\**\*" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="Data\Migrations\*.resx" />
  </ItemGroup>
</Project>
